platform :osx, '10.8'

pod 'AFNetworking', '~> 1.3.0'
pod 'AFOAuth2Client', '~> 0.1.1'
pod 'JAListView', '~> 0.0.1'
pod 'Mantle', '~> 1.1'
pod 'OBMenuBarWindow', '~> 0.0.1'
pod 'ReactiveCocoa', '~> 1.9.4'
pod 'RHPreferences', '~> 1.0.0'
pod 'SORelativeDateTransformer', '~> 1.1.8'
pod 'StartAtLoginController', '~> 0.0.1'
