platform :osx, '10.8'

pod 'AFNetworking', '~> 1.3.3'
pod 'AFOAuth2Client', '~> 0.1.2'
pod 'CocoaLumberjack', '~> 1.8.0'
pod 'INAppStoreWindow', '~> 1.4'
pod 'JAListView', '~> 0.0.1'
pod 'HexColors', '~> 2.2.1'
pod 'Mantle', '~> 1.1'
pod 'Reachability', '~> 3.1.0'
pod 'ReactiveCocoa', '~> 2.2.3'
pod 'RHPreferences', '~> 1.0.0'
pod 'SORelativeDateTransformer', '~> 1.1.9'
pod 'StartAtLoginController', '~> 0.0.1'
