platform :osx, '10.8'

pod 'AFNetworking', '~> 1.3.1'
pod 'AFOAuth2Client', '~> 0.1.1'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'JAListView', '~> 0.0.1'
pod 'HexColors', '~> 2.0.0'
pod 'Mantle', '~> 1.1'
pod 'ReactiveCocoa', '~> 1.9.5'
pod 'RHPreferences', '~> 1.0.0'
pod 'SORelativeDateTransformer', '~> 1.1.9'
pod 'StartAtLoginController', '~> 0.0.1'
